### ISSUE TITLE
Can't get it working?

### ISSUE THREAD

**Issue by benedict-w** [gwa/grunt-gettext-parser#3]
Sorry I am having an issue getting this working:

What should the value of 'your_target' be?

When I `grunt gettext_parser` this:

``` node
gettext_parser: {
    your_target: {
        options: {
            style: 'wordpress',
            textdomain: '<%= pkg.name %>'
         },
        'lang/output.php': ['views/**/*.twig']
    }
},
```

I get `Running "gettext_parser:your_target" (gettext_parser) task`, but nothing appears to have happened.

When I `grunt gettext_parser` this (removing your_target):

``` node
gettext_parser: {
    options: {
        style: 'wordpress',
        textdomain: '<%= pkg.name %>'
    },
    'lang/output.php': ['views/**/*.twig']
},
```

My output.php file is created, but it's content is only:

``` php
<?php
;
```

**Comment by gwagroves** [comment]
Do you have any templates that match `views/**/*.twig`?

**Comment by benedict-w** [comment]
Yes my .twig files are in the views folder

**Comment by gwagroves** [comment]
What do the translation calls in the twig templates look like?

**Comment by benedict-w** [comment]
Usually `__()`

**Comment by gwagroves** [comment]
The script expects this:

```
{{ __('My string', 'mydomain')  }}
```

**Comment by benedict-w** [comment]
Yes that is what I do.

**Comment by craigiswayne** [comment]
i just tested it out without a domain as well, doesnt work... this script requires a textdomain to be set in the grunt config which matches the text domain used for translatables.

which is a pity really

**Comment by craigiswayne** [comment]
Additionally in the README.md it says this:

> ### textdomain
> Wordpress only: The textdomain to be parsed. gettext calls to other domains will be ignored. Set to null to parse all text domains.

but tried the **null** value and that doesnt work as expected

**Comment by gwagroves** [comment]
@craigiswayne I'll test it with `null` as the textdomain.
