### ISSUE TITLE
Config option to override gettext function

### ISSUE THREAD

**Issue by mdrubba** [gwa/grunt-gettext-parser#4]
I am using https://github.com/cedaro/grunt-wp-i18n/ for my translation process and until now I passed the translation strings with the context to the twig files. My projects are growing and now I need another solution for this.

I found your plugin but it's not compatible with the mentioned wp-i18n process. Do you think it's possible to add another option to define the output function? I already forked the repo and created a solution. Will create a pull request. Would be nice if you can check it out.

**Comment by gwagroves** [comment]
Merged and released.

**Comment by mdrubba** [comment]
@gwagroves Hey thanks for accepting the pull request and for writing the tests and all the stuff. I think you forgot changing the version in the package.json.

**Comment by gwagroves** [comment]
@drumba True, I forgot.
